[2024-04-20T12:57:21.289+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-20T12:57:21.301+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: profile_creation_dag.create_profiles manual__2024-04-20T12:57:17.713717+00:00 [queued]>
[2024-04-20T12:57:21.304+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: profile_creation_dag.create_profiles manual__2024-04-20T12:57:17.713717+00:00 [queued]>
[2024-04-20T12:57:21.305+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-20T12:57:21.310+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): create_profiles> on 2024-04-20 12:57:17.713717+00:00
[2024-04-20T12:57:21.325+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-20T12:57:21.329+0000] {standard_task_runner.py:63} INFO - Started process 72 to run task
[2024-04-20T12:57:21.328+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'profile_creation_dag', 'create_profiles', 'manual__2024-04-20T12:57:17.713717+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sample-project-dag.py', '--cfg-path', '/tmp/tmpcyishuvs']
[2024-04-20T12:57:21.329+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask create_profiles
[2024-04-20T12:57:21.363+0000] {task_command.py:426} INFO - Running <TaskInstance: profile_creation_dag.create_profiles manual__2024-04-20T12:57:17.713717+00:00 [running]> on host 670df62afafc
[2024-04-20T12:57:21.402+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='profile_creation_dag' AIRFLOW_CTX_TASK_ID='create_profiles' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T12:57:17.713717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T12:57:17.713717+00:00'
[2024-04-20T12:57:21.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-20T12:57:21.405+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-20T12:57:21.405+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sample-project-dag.py", line 84, in profile_creation
    main()
  File "/opt/airflow/dags/scripts/superstore_script.py", line 64, in main
    conn = sqlite3.connect('/sqlite_db_directory/Retail_data.db')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
[2024-04-20T12:57:21.411+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=profile_creation_dag, task_id=create_profiles, execution_date=20240420T125717, start_date=20240420T125721, end_date=20240420T125721
[2024-04-20T12:57:21.417+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task create_profiles (unable to open database file; 72)
[2024-04-20T12:57:21.433+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-20T12:57:21.440+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-20T12:57:21.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
